import { getProjects } from "@/lib/projects";
import ProjectGrid from "@/components/ProjectGrid";
import OfficialProjects from "@/components/OfficialProjects";

export default async function Home() {
  const projects = await getProjects();
  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6">
      <header className="space-y-2">
        <h1 className="text-2xl font-bold">Automated Portfolio</h1>
        <p className="text-sm text-black/60 dark:text-white/60">Generated by Portfolio-OPs</p>
      </header>
      <OfficialProjects />
      <h1 className="text-2xl font-bold">All Projects</h1>
      <ProjectGrid projects={projects} />
    </div>
  );
}
